eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

spring:
  application:
    name: ToDoList

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.vdaeaddazojbejcrndfj&password=FU963!omsd@5061K
    username: postgres.vdaeaddazojbejcrndfj
    password: FU963!omsd@5061K
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

main:
  banner-mode: off